# Use Node.js 22
FROM node:22-trixie-slim

WORKDIR /app

# Copy only package.json and package-lock.json to leverage Docker cache
COPY logger-service/package*.json ./logger-service/
RUN cd logger-service && npm install

# Copy full service code and proto
COPY logger-service ./logger-service
COPY proto ./proto

WORKDIR /app/logger-service

RUN npm run build

# Start the service
CMD ["node", "dist/main.js"]
