# Use Node.js 22
FROM node:22-trixie-slim

WORKDIR /app

# Copy only package.json and package-lock.json to leverage Docker cache
COPY filter-service/package*.json ./filter-service/
RUN cd filter-service && npm install

# Copy full service code and proto
COPY filter-service ./filter-service
COPY proto ./proto

WORKDIR /app/filter-service

RUN npm run build

# Expose GRPC port
EXPOSE 50052

# Start the service
CMD ["node", "dist/main.js"]
